version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: "monthly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
