# Text for `site.*`
title: Jekyll theme for one-page README.md
description: Jekyll theme for one-page README.md
logo_url: https://avatars.githubusercontent.com/u/117988194?s=200&v=4
repository: gomzyakov/achievements-theme
url: https://gomzyakov.github.io/achievements-theme/
baseurl: ""

permalinks: pretty

include:
  - CONTRIBUTING.md
  - LICENSE

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-avatar
  - jemoji
  - jekyll-mentions

# Exclude the `vendor` folder created by build process
exclude:
  - vendor

# To replace the standard GitHub metadata if it fails: https://help.github.com/articles/repository-metadata-on-github-pages/
license:
  key: eupl
  name: European Union Public License 1.2
  spdx_id: EUPL-1.2

# Add a custom copyright message
# copyright: Foundation for Public Code

defaults:
  -
    scope:
      path: "index.md"
    values:
      order: 0 # Show the index at the top of the navigation
  -
    scope:
      path: "LICENSE.md"
    values:
      order: 100 # Show the license at the bottom of the navigation

titles_from_headings:
  strip_title: true

syntax_highlighter: rouge
